#+title:   Situs Est: A Static Site Generator
#+author:  Stephen R. Kifer

* Introduction

SitusEst was created because there does not appear to be anything
available that exactly provides what I am looking for in a static site
generator. So I decided just write my own and see where it goes.

** Development Goals and Principles

In no particular order, here are goals and principles motivating and
guiding this work:
- Written in a compiled language (probably C)
- Minimal dependencies
- Use org mode files as the primary input for content
- Have a clearly defined relationship between structure and semantic
  HTML output
- Rigourously use semantic versioning without hiding behind 0.x.x forever
- Include support for raw HTML and Markdown; Markdown version would
  either be CommonMark or Pandoc Markdown
- Flexible support for running daily/hourly/etc on server to
  effecively update site pages
- Follow standards as much as possible

** Status

This is still in a very early stage of development and is not yet usable.

* SitusEst Format

** Directory Structure

Each SiteEst site has a sourece directory from which it is created.
The source directory structure is duplicated in the HTML website
output. How files are transformed is determined by their filename
suffix and any configuration files that provide variables and
templates to shape the final output.

** File Transformations

*** Org Mode Files (*.org)

*** Raw Files (HTML)
